# Basic reverse proxy to PHP-FPM container

server {
    listen 80;
    server_name localhost;

    root /var/www/html/public; # public folder is web root
    index index.php index.html;

    location / {
        # Try file, then route to index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Send PHP scripts to PHP-FPM container
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
